### PR TITLE
Support source maps

### PR DESCRIPTION
**Pull request by homburg**

### CODE REVIEW

**Review by goto-bus-stop — APPROVED** [review]
Thanks!

**Comment by goto-bus-stop** [comment]
@homburg Would you like to have commit & publish access on this package?
I was only using this plugin in one project that has since moved away from rollup, so if something breaks I probably won't notice 😇

**Comment by homburg** [comment]
You're welcome 👍 And sure, commit and publish would make everything easier :-)

**Comment by goto-bus-stop** [comment]
I think I added you both on github and npm, so you should be able to merge this PR :)

When doing a release I like to write a bullet point list in changelog.md and manually update the version number in package.json:
https://github.com/goto-bus-stop/rollup-plugin-es-module-interop/commit/d9a02a7cde25df5cf328b4a317f2fbe436619ced
Personally I manually do `git commit` and `git tag vVERSION` and then `npm publish` afterward. If you already have a different release process that you like that's fine too—no sense in being strict about that stuff for a tiny package like this :)

**Comment by homburg** [comment]
Thanks! I don't think I've ever published before. So I'll just follow your instructions :)

**Comment by goto-bus-stop** [comment]
sweet, ok :) let me know if you have any questions!

**Comment by homburg** [comment]
Did it! Thank you for the guide 👍

**Pull request merged**
